import streamlit as st
import os
from PIL import Image

st.set_page_config(page_title="Media Mix Model Dashboard", layout="wide", page_icon="📊")

st.title("📊 Media Mix Model (MMM) Dashboard")
st.markdown("Welcome to the interactive dashboard for your Media Mix Model. Review your generated insights, ROAS analysis, and model accuracy below.")

# Create tabs for different sections
tab1, tab2, tab3 = st.tabs(["📈 Visualizations", "📄 ROAS Analysis", "📝 Final Report"])

with tab1:
    st.header("Model Visualizations")
    visuals_dir = "visuals"
    if os.path.exists(visuals_dir):
        # Find all images in the visuals directory
        images = sorted([f for f in os.listdir(visuals_dir) if f.endswith(('.png', '.jpg', '.jpeg'))])
        if not images:
            st.info("No visualizations found. Please ensure you have run the main pipeline.")
        else:
            # Display each image
            for img_name in images:
                st.subheader(img_name.replace(".png", "").replace("_", " ").title())
                img_path = os.path.join(visuals_dir, img_name)
                try:
                    image = Image.open(img_path)
                    st.image(image, use_container_width=True)
                except Exception as e:
                    st.error(f"Error loading image {img_name}: {e}")
    else:
        st.warning("Visuals folder not found. Please run the pipeline first.")

with tab2:
    st.header("ROAS (Return on Ad Spend) Analysis")
    report_path = "reports/roas_analysis.md"
    if os.path.exists(report_path):
        with open(report_path, "r") as f:
            st.markdown(f.read())
    else:
        st.info("ROAS report not found. Please run the pipeline first.")

with tab3:
    st.header("Executive Summary")
    docs_path = "docs/final_report.md"
    if os.path.exists(docs_path):
        with open(docs_path, "r") as f:
            st.markdown(f.read())
    else:
        st.info("Final report not found. Please run the pipeline first.")

st.sidebar.title("Information")
st.sidebar.info("This dashboard reads the outputs generated by your `src.pipeline` script. If you update your data and re-run the pipeline, simply refresh this page to see the new results!")
