"""Data ingestion, validation, and preprocessing for MMM."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from .feature_engineering import geometric_adstock, hill_saturation


@dataclass
class DataProcessingResult:
    df: pd.DataFrame
    spend_columns: List[str]
    revenue_column: str
    synthetic_data_generated: bool
    data_quality_notes: List[str]


def _identify_date_column(df: pd.DataFrame) -> str:
    candidates = [
        col
        for col in df.columns
        if col.strip().lower() in {"date", "week", "week_start", "timestamp"}
    ]
    if candidates:
        return candidates[0]
    return df.columns[0]


def _to_week_start(date_series: pd.Series) -> pd.Series:
    date_series = pd.to_datetime(date_series, errors="coerce")
    return date_series - pd.to_timedelta(date_series.dt.weekday, unit="D")


def _generate_synthetic_inputs(
    media_path: Path,
    revenue_path: Path,
    marker_path: Path,
    seed: int = 42,
) -> None:
    rng = np.random.default_rng(seed)
    n_weeks = 156
    weeks = pd.date_range("2023-01-02", periods=n_weeks, freq="W-MON")
    t = np.arange(n_weeks)

    search = 26000 + 3500 * np.sin(2 * np.pi * t / 52) + rng.normal(0, 2200, size=n_weeks)
    social = 18000 + 2600 * np.cos(2 * np.pi * t / 26) + rng.normal(0, 1800, size=n_weeks)
    tv_pulse = (rng.uniform(0, 1, size=n_weeks) > 0.68).astype(float)
    tv = 28000 + 9000 * tv_pulse + rng.normal(0, 2700, size=n_weeks)

    search = np.clip(search, 1500, None)
    social = np.clip(social, 1200, None)
    tv = np.clip(tv, 2000, None)

    search_scale = float(np.max(search))
    social_scale = float(np.max(social))
    tv_scale = float(np.max(tv))

    search_x = hill_saturation(geometric_adstock(search / search_scale, theta=0.45), alpha=1.20, gamma=0.55)
    social_x = hill_saturation(geometric_adstock(social / social_scale, theta=0.35), alpha=1.10, gamma=0.60)
    tv_x = hill_saturation(geometric_adstock(tv / tv_scale, theta=0.65), alpha=1.45, gamma=0.70)

    baseline = 145000 + 280 * t + 8500 * np.sin(2 * np.pi * t / 52)
    revenue = (
        baseline
        + 65000 * search_x
        + 43000 * social_x
        + 50000 * tv_x
        + rng.normal(0, 4200, size=n_weeks)
    )
    revenue = np.clip(revenue, 1000, None)

    media_df = pd.DataFrame(
        {
            "Date": weeks,
            "Search": np.round(search, 2),
            "Social": np.round(social, 2),
            "TV": np.round(tv, 2),
        }
    )
    revenue_df = pd.DataFrame({"Date": weeks, "Revenue": np.round(revenue, 2)})

    # Inject small missingness to validate imputation branch.
    for col in ["Search", "Social", "TV"]:
        missing_idx = rng.choice(n_weeks, size=2, replace=False)
        media_df.loc[missing_idx, col] = np.nan
    revenue_missing_idx = rng.choice(n_weeks, size=2, replace=False)
    revenue_df.loc[revenue_missing_idx, "Revenue"] = np.nan

    media_df.to_csv(media_path, index=False)
    revenue_df.to_csv(revenue_path, index=False)
    marker_path.parent.mkdir(parents=True, exist_ok=True)
    marker_path.write_text(
        "Synthetic inputs generated by src.data_processing._generate_synthetic_inputs\\n",
        encoding="utf-8",
    )


def _prepare_media_df(media_df: pd.DataFrame) -> Tuple[pd.DataFrame, List[str], str]:
    date_col = _identify_date_column(media_df)
    spend_cols = [col for col in media_df.columns if col != date_col]
    if not spend_cols:
        raise ValueError("Media spend file must include at least one spend column")

    for col in spend_cols:
        media_df[col] = pd.to_numeric(media_df[col], errors="coerce")

    media_df[date_col] = _to_week_start(media_df[date_col])
    media_df = media_df.dropna(subset=[date_col])
    media_weekly = media_df.groupby(date_col, as_index=False)[spend_cols].sum(min_count=1)
    media_weekly = media_weekly.rename(columns={date_col: "Date"})
    return media_weekly, spend_cols, date_col


def _prepare_revenue_df(revenue_df: pd.DataFrame) -> Tuple[pd.DataFrame, str]:
    date_col = _identify_date_column(revenue_df)
    value_cols = [col for col in revenue_df.columns if col != date_col]
    if not value_cols:
        raise ValueError("Revenue file must include a revenue column")

    revenue_col = value_cols[0]
    revenue_df[revenue_col] = pd.to_numeric(revenue_df[revenue_col], errors="coerce")
    revenue_df[date_col] = _to_week_start(revenue_df[date_col])
    revenue_df = revenue_df.dropna(subset=[date_col])
    revenue_weekly = revenue_df.groupby(date_col, as_index=False)[revenue_col].sum(min_count=1)
    revenue_weekly = revenue_weekly.rename(columns={date_col: "Date", revenue_col: "Revenue"})
    return revenue_weekly, "Revenue"


def _impute_missing(df: pd.DataFrame, spend_cols: List[str], revenue_col: str) -> Dict[str, int]:
    missing_before = df.isna().sum().to_dict()

    for col in spend_cols:
        df[col] = df[col].interpolate(method="linear", limit_direction="both")
        df[col] = df[col].fillna(df[col].median())

    df[revenue_col] = df[revenue_col].interpolate(method="linear", limit_direction="both")
    df[revenue_col] = df[revenue_col].fillna(df[revenue_col].median())

    missing_after = df.isna().sum().to_dict()

    return {
        "missing_before_total": int(sum(missing_before.values())),
        "missing_after_total": int(sum(missing_after.values())),
    }


def _find_high_correlation_pairs(df: pd.DataFrame, threshold: float = 0.80) -> List[Tuple[str, str, float]]:
    corr = df.corr(numeric_only=True)
    pairs: List[Tuple[str, str, float]] = []
    cols = corr.columns.tolist()
    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            val = corr.iloc[i, j]
            if np.isfinite(val) and abs(val) >= threshold:
                pairs.append((cols[i], cols[j], float(val)))
    return sorted(pairs, key=lambda x: abs(x[2]), reverse=True)


def _save_correlation_matrix(df: pd.DataFrame, output_path: Path) -> None:
    corr = df.corr(numeric_only=True)
    plt.figure(figsize=(8, 6))
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="Blues", square=True)
    plt.title("Correlation Matrix")
    plt.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=180)
    plt.close()


def _write_data_quality_report(
    output_path: Path,
    df: pd.DataFrame,
    spend_cols: List[str],
    imputation_stats: Dict[str, int],
    high_corr_pairs: List[Tuple[str, str, float]],
    synthetic_data_generated: bool,
) -> None:
    lines = []
    lines.append("# Data Quality Report")
    lines.append("")
    lines.append("## Dataset Overview")
    lines.append(f"- Rows: {len(df)}")
    lines.append(f"- Columns: {len(df.columns)}")
    lines.append(f"- Date range: {df['Date'].min().date()} to {df['Date'].max().date()}")
    lines.append(f"- Spend channels: {', '.join(spend_cols)}")
    lines.append(f"- Synthetic data generated: {'Yes' if synthetic_data_generated else 'No'}")
    lines.append("")

    lines.append("## Validation Checks")
    lines.append(f"- Unique weekly dates: {df['Date'].is_unique}")
    lines.append(f"- Monotonic date index: {df['Date'].is_monotonic_increasing}")
    lines.append(f"- Missing values before imputation: {imputation_stats['missing_before_total']}")
    lines.append(f"- Missing values after imputation: {imputation_stats['missing_after_total']}")
    lines.append("")

    lines.append("## Missing Data Handling")
    lines.append("- Spend columns: linear interpolation followed by median fallback.")
    lines.append("- Revenue: linear interpolation followed by median fallback.")
    lines.append("- Rationale: interpolation preserves short-run temporal continuity in weekly series; median fallback prevents null leakage for model training.")
    lines.append("")

    lines.append("## Multicollinearity Diagnostics")
    lines.append("- Threshold for high correlation: |r| >= 0.80")
    if high_corr_pairs:
        for left, right, value in high_corr_pairs:
            lines.append(f"- {left} vs {right}: r = {value:.3f}")
    else:
        lines.append("- No highly correlated variable pairs found above threshold.")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def process_data(
    project_root: Path,
    media_filename: str = "Weekly_Media_Spend.csv",
    revenue_filename: str = "Weekly_Revenue.csv",
) -> DataProcessingResult:
    """Load, validate, merge, impute, and persist model-ready weekly data."""

    media_path = project_root / media_filename
    revenue_path = project_root / revenue_filename
    synthetic_marker_path = project_root / "data" / "synthetic_input_marker.txt"

    synthetic_data_generated = False
    notes: List[str] = []

    if not media_path.exists() or not revenue_path.exists():
        _generate_synthetic_inputs(media_path, revenue_path, synthetic_marker_path, seed=42)
        synthetic_data_generated = True
        notes.append(
            "Input files were missing; generated deterministic synthetic weekly spend/revenue data for reproducible demonstration."
        )
    elif synthetic_marker_path.exists():
        synthetic_data_generated = True
        notes.append(
            "Using previously generated deterministic synthetic weekly spend/revenue data."
        )

    media_df = pd.read_csv(media_path)
    revenue_df = pd.read_csv(revenue_path)

    media_weekly, spend_cols, _ = _prepare_media_df(media_df)
    revenue_weekly, revenue_col = _prepare_revenue_df(revenue_df)

    merged = pd.merge(media_weekly, revenue_weekly, on="Date", how="outer")
    merged = merged.sort_values("Date").reset_index(drop=True)

    imputation_stats = _impute_missing(merged, spend_cols=spend_cols, revenue_col=revenue_col)

    merged = merged.sort_values("Date").drop_duplicates(subset=["Date"], keep="last")
    merged = merged.reset_index(drop=True)

    # Ensure all modeled columns are non-negative after cleaning.
    for col in spend_cols + [revenue_col]:
        merged[col] = np.clip(merged[col], 0.0, None)

    if merged[spend_cols + [revenue_col]].isna().any().any():
        raise ValueError("Null leakage detected after imputation")

    processed_path = project_root / "data" / "processed_data.csv"
    processed_path.parent.mkdir(parents=True, exist_ok=True)

    out_df = merged.copy()
    out_df["Date"] = pd.to_datetime(out_df["Date"]).dt.strftime("%Y-%m-%d")
    out_df.to_csv(processed_path, index=False)

    corr_plot_path = project_root / "visuals" / "correlation_matrix.png"
    _save_correlation_matrix(merged[spend_cols + [revenue_col]], corr_plot_path)

    high_corr_pairs = _find_high_correlation_pairs(merged[spend_cols + [revenue_col]], threshold=0.80)

    report_path = project_root / "reports" / "data_quality_report.md"
    _write_data_quality_report(
        output_path=report_path,
        df=merged,
        spend_cols=spend_cols,
        imputation_stats=imputation_stats,
        high_corr_pairs=high_corr_pairs,
        synthetic_data_generated=synthetic_data_generated,
    )

    return DataProcessingResult(
        df=merged,
        spend_columns=spend_cols,
        revenue_column=revenue_col,
        synthetic_data_generated=synthetic_data_generated,
        data_quality_notes=notes,
    )
